version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
    - DB_URL=jdbc:postgresql://db.fkjwjgbotfrgimmwvavu.supabase.co:5432/postgres?user=postgres&password=aDsoGw7C5NzaZUCp
      

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

